const N = {x: 0, y: -25};
const S = {x: 0, y: 25};
const E = {x: 25, y: 0};
const W = {x: -25, y: 0};
const NE = {x: 25, y: -25};
const NW = {x: -25, y: -25};
const SE = {x: 25, y: 25};
const SW = {x: -25, y: 25};
// should have used a class: const direction = (x, y) { return {x, y} };
